name = "disidencia-incontrolada"
compatibility_date = "2024-08-01"

# Solo para deployment manual con Wrangler CLI
[assets]
directory = "./public_html"
not_found_handling = "404-page"

# Variables de entorno para producción  
[vars]
ENVIRONMENT = "production"
