name: Build from emacs org and deploy to Cloudflare Workder
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Emacs
        run: |
          sudo apt-get update
          sudo apt-get install -y emacs-nox
            
      - name: Build static files
        run: |
          chmod +x build.sh
          bash build.sh
            
      - name: Verify build output
        run: |
          ls -la public_html/

      - name: Deploy to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: disidencia-incontrolada
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
